var allItems=[],activeTab="updates",activeGuide="",activeCheat="cmds",upFilter="all";
function swTab(n){activeTab=n;document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active")});document.querySelectorAll(".topbar-nav button").forEach(function(b,i){b.classList.toggle("active",["updates","guide","cheats","about"][i]===n)});document.getElementById("tab-"+n).classList.add("active")}
function loadData(){var list=document.getElementById("upList");if(window.MAD_DATA&&window.MAD_DATA.items&&window.MAD_DATA.items.length){allItems=window.MAD_DATA.items;try{localStorage.setItem("mi_data",JSON.stringify(window.MAD_DATA))}catch(e){}updateCounts();renderUp()}else{try{var c=localStorage.getItem("mi_data");if(c){var d=JSON.parse(c);if(d.items&&d.items.length){allItems=d.items;updateCounts();renderUp();return}}}catch(e){}list.innerHTML='<div class="empty"><span class="ic">📭</span><h3>暂无数据</h3><p>运行 <code>node mad-island-tracker.js --full</code></p></div>'}}
function updateCounts(){var o={content:0,minor:0,bugfix:0,hotfix:0};for(var i=0;i<allItems.length;i++){var it=allItems[i];if(it.type==="🟢 主要内容")o.content++;else if(it.type==="🔵 小更新")o.minor++;else if(it.type==="🔴 热修复")o.hotfix++;else o.bugfix++}document.getElementById("cnt-all").textContent=allItems.length;document.getElementById("cnt-content").textContent=o.content;document.getElementById("cnt-minor").textContent=o.minor;document.getElementById("cnt-bugfix").textContent=o.bugfix;document.getElementById("cnt-hotfix").textContent=o.hotfix}
function setFilter(f){upFilter=f;document.querySelectorAll("#tab-updates .side-item").forEach(function(b){b.classList.remove("active")});var idx={all:0,content:1,minor:2,bugfix:3,hotfix:4}[f]||0;document.querySelectorAll("#tab-updates .side-item")[idx].classList.add("active");renderUp()}
function renderUp(){var q=(document.getElementById("upSearch")?.value||"").toLowerCase();var items=allItems;if(upFilter==="content")items=items.filter(function(it){return it.type==="🟢 主要内容"});else if(upFilter==="minor")items=items.filter(function(it){return it.type==="🔵 小更新"});else if(upFilter==="bugfix")items=items.filter(function(it){return it.type==="🟡 Bug修复"});else if(upFilter==="hotfix")items=items.filter(function(it){return it.type==="🔴 热修复"});if(q)items=items.filter(function(it){return it.title.indexOf(q)>-1||it.content.indexOf(q)>-1||it.title_en.toLowerCase().indexOf(q)>-1});var list=document.getElementById("upList");if(!items.length){list.innerHTML='<div class="empty"><span class="ic">🔎</span><h3>无匹配</h3></div>';return}var h="",lm="";for(var i=0;i<items.length;i++){var it=items[i];var ym=it.date_str.substring(0,7);if(ym!==lm){lm=ym;h+='<div class="u-group-title">'+ym+'</div>'}var cls="t2",tagC="t-f",label="Bug修复";if(it.type==="🟢 主要内容"){cls="t0";tagC="t-c";label="新增内容"}else if(it.type==="🔵 小更新"){cls="t1";tagC="t-m";label="小更新"}else if(it.type==="🔴 热修复"){cls="t3";tagC="t-h";label="热修复"}var body=it.content.replace(/\n/g,"<br>").replace(/新增/g,'<span class="hl-a">新增</span>').replace(/修复/g,'<span class="hl-f">修复</span>');h+='<div class="u-card '+cls+'"><div class="u-head"><span class="u-ver">'+esc(it.title)+'</span><div><span class="u-tag '+tagC+'">'+label+'</span><span class="u-date">'+it.date_str.substring(5)+'</span></div></div><div class="u-body">'+body+'</div></div>'}list.innerHTML=h}
function esc(s){var d=document.createElement("div");d.textContent=s;return d.innerHTML}

var G=GUIDE_DATA_PLACEHOLDER;

function buildGuideSidebar(filter){var el=document.getElementById("guideSidebar");var h="";for(var i=0;i<G.length;i++){var g=G[i];if(filter&&g.t.indexOf(filter)===-1&&g.id.indexOf(filter)===-1)continue;h+='<button class="side-item'+(activeGuide===g.id?" active":"")+'" onclick="selGuide(\''+g.id+'\')" data-gid="'+g.id+'"><span class="emoji">'+g.e+'</span><span class="lab">'+g.t+'</span></button>'}el.innerHTML=h||'<div style="padding:12px;color:var(--muted);font-size:11px">无匹配</div>'}
function selGuide(id){activeGuide=id;document.querySelectorAll("[data-gid]").forEach(function(b){b.classList.toggle("active",b.dataset.gid===id)});document.querySelectorAll("#guideMain section").forEach(function(s){s.style.display=s.dataset.id===id?"block":"none"});localStorage.setItem("mi_guide",id)}
function filterGuideSidebar(){var q=document.getElementById("guideSearch")?.value||"";buildGuideSidebar(q);if(q){document.querySelectorAll("#guideMain section").forEach(function(s){s.style.display=s.dataset.id.indexOf(q)>-1||s.textContent.indexOf(q)>-1?"block":"none"})}else{document.querySelectorAll("#guideMain section").forEach(function(s){s.style.display=s.dataset.id===activeGuide?"block":"none"})}}
function initGuide(){var main=document.getElementById("guideMain");var h="";for(var i=0;i<G.length;i++){var g=G[i];h+='<section data-id="'+g.id+'" style="display:none">'+g.h+'</section>'}main.innerHTML=h;buildGuideSidebar();selGuide(localStorage.getItem("mi_guide")||G[0].id)}
function selCheat(id){activeCheat=id;document.querySelectorAll("[data-ctab]").forEach(function(b){b.classList.toggle("active",b.dataset.ctab===id)});document.getElementById("cheatSearch").value="";renderCheats()}
function renderCheats(){var q=(document.getElementById("cheatSearch")?.value||"").toLowerCase();var data=window.CHEATS_DATA;if(!data)return;var val=data[activeCheat];if(!val)return;var panel=document.getElementById("cheatPanels");var h="";if(val&&typeof val==="object"&&!Array.isArray(val)){var keys=Object.keys(val);for(var ki=0;ki<keys.length;ki++){var cat=keys[ki];var arr=val[cat];var f=arr;if(q)f=arr.filter(function(r){return r[0].toLowerCase().indexOf(q)>-1||r[1].indexOf(q)>-1});if(!f.length)continue;h+='<h3 style="color:var(--amber);font-size:14px;margin:16px 0 8px">'+cat+" ("+f.length+")</h3>";h+='<div class="tbl"><table><thead><tr><th>代码</th><th>名称</th></tr></thead><tbody>';for(var i=0;i<f.length;i++){var r=f[i];h+='<tr><td style="font-family:var(--mono);font-size:11px;color:var(--green);white-space:nowrap">'+esc(r[0])+"</td><td>"+esc(r[1])+"</td></tr>"}h+="</tbody></table></div>"}}else if(Array.isArray(val)){var f=val;if(q)f=val.filter(function(r){return r[0].toLowerCase().indexOf(q)>-1||r[1].indexOf(q)>-1});h+='<div class="tbl"><table><thead><tr><th>代码</th><th>效果</th></tr></thead><tbody>';for(var i=0;i<f.length;i++){var r=f[i];h+='<tr><td style="font-family:var(--mono);font-size:11px;color:var(--green);white-space:nowrap">'+esc(r[0])+"</td><td>"+esc(r[1])+"</td></tr>"}h+="</tbody></table></div>"}panel.innerHTML=h||'<div class="empty"><span class="ic">🔎</span><h3>无匹配</h3></div>'}
initGuide();loadData();selCheat("cmds");
setTimeout(function(){var g=document.getElementById("aboutNums");if(g){var cd=0;if(window.CHEATS_DATA){var vals=Object.values(window.CHEATS_DATA);for(var i=0;i<vals.length;i++){var v=vals[i];if(Array.isArray(v))cd+=v.length;else if(typeof v==="object"){var ks=Object.keys(v);for(var j=0;j<ks.length;j++)cd+=v[ks[j]].length}}}g.innerHTML='<div class="nc"><div class="big">'+(allItems.length||0)+'</div><div class="lbl">追踪更新</div></div><div class="nc"><div class="big">'+G.length+'</div><div class="lbl">攻略章节</div></div><div class="nc"><div class="big">'+cd+'</div><div class="lbl">作弊码条目</div></div><div class="nc"><div class="big">24/12</div><div class="lbl">时间范围</div></div>'}},300);
