// Mad Island 更新数据 — 由追踪脚本自动生成
// 生成时间：2026-06-19T02:43:59.651Z
window.MAD_DATA = {
  "app_id": "2739590",
  "generated_at": "2026-06-19T02:43:59.651Z",
  "total": 50,
  "manual_translated": 50,
  "items": [
    {
      "adult": true,
      "gid": "1832065502821220",
      "title": "update v0.5.10.2 [beta]",
      "title_en": "update v0.5.10.2 [beta]",
      "date": 1778503984,
      "date_str": "2026-05-12 04:53",
      "author": "emadeplus",
      "content": "修复了多个 Bug：达摩的四肢显示异常、地下矿井室内过亮、睡眠切换场景时环境光照残留为室外配置。洞穴猿体型从大型调整为中型。束缚锁链界面现在显示表情和层的 ID。",
      "content_en": "Bug FixesSeveral bug fixes have been implemented.FixesFixed visual bugs (Daruma limbs not displaying correctly, interiors in the Underground Mine being too bright)Fixed several other bugsFixed an issue where, after sleeping or similar transitions, moving to another stage before the environment color finished updating could cause the environment lighting to remain set to the outdoor configurationAdjusted the Cave Ape size type from Large to MediumAdjusted the Restraint Chain UI to display the IDs for Expression and Layer Type.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1832065502821220",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1832065502817698",
      "title": "update v0.5.10.1 [beta]",
      "title_en": "update v0.5.10.1 [beta]",
      "date": 1778340810,
      "date_str": "2026-05-10 07:33",
      "author": "emadeplus",
      "content": "热修复：修复了伐木场和采矿场奖励未正确应用的关键 Bug。",
      "content_en": "HotfixA critical bug has been fixed.FixesFixed an issue where rewards from the Logging Site and Mining Site were not being applied correctly.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1832065502817698",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1832065502817441",
      "title": "update v0.5.10 [beta]",
      "title_en": "update v0.5.10 [beta]",
      "date": 1778329576,
      "date_str": "2026-05-10 04:26",
      "author": "emadeplus",
      "content": "新增挤奶机（支持大型女性原住民、大型女孩）、达摩（大型女孩）、2 个新动物 NPC、地下矿井场景。女性原住民支持束缚。新增场景背景音乐曲目和多种新物品。修复了无脸木乃伊放入挤奶机时动画停止、武器斩击特效偶尔不显示等问题。",
      "content_en": "Beta Version NoticeThis version requires opting into the beta branch to play. Please note that stability is not guaranteed, and we strongly recommend using a separate save file when playing this version.AdditionsMilking Machine (Large Female Native, Large Girl)Daruma (Large Girl)Added 2 new animal NPCsAdded new stage: Underground MineAdded Restraint support for Female NativesAdded new field BGM tracksAdded several new itemsFixes & AdjustmentsFixed an issue where animations would stop when placing a faceless Mummy into the Milking MachineFixed an issue where weapon slash effects and other effects would sometimes fail to appearAdjusted the items obtainable from NPC jobsFixed several visual bugsExternal Content Update2 New H scenes",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1832065502817441",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1829528821303698",
      "title": "update v0.5.9.1 [beta]",
      "title_en": "update v0.5.9.1 [beta]",
      "date": 1775641315,
      "date_str": "2026-04-09 01:41",
      "author": "emadeplus",
      "content": "热修复：修复繁殖设施无法运作的关键 Bug。修复多个视觉问题。部分 NPC 现在可使用怀孕加速器。调整了青年男性 H 场景中的怀孕判定。",
      "content_en": "HotfixA critical bug has been fixed.Fixes & AdjustmentsFixed an issue where breeding at the Breeding Facility was no longer functioningFixed several visual bugsAdjusted so that some NPCs can now use the Pregnancy AcceleratorAdjusted pregnancy checks for some NPCs during H scenes with Young Men",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1829528821303698",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1828894815567183",
      "title": "update v0.5.9 [beta]",
      "title_en": "update v0.5.9 [beta]",
      "date": 1775563309,
      "date_str": "2026-04-08 04:01",
      "author": "emadeplus",
      "content": "新增 H 场景：约娜×儿子（普通）、少女×男性（强制）。新增拆解（儿子）、绞刑架、断头台、钩子、沙袋、木马（均支持少女和胖青年）。达摩新增少女外观变体。挤奶机支持少女、木乃伊、地下女性。修复小型原住民地图 NPC 不再佩戴三角帽等问题。扩展了多个 NPC 的怀孕支持和设施兼容性。",
      "content_en": "New H ScenesYona × Son (Normal)Maiden × Male (Forced)AdditionsDismantling (Son)Gallows ( Maiden, Fat Young Man)Guillotine (Maiden, Fat Young Man)Hooks (Maiden, Fat Young Man)Punching Bag (Maiden, Fat Young Man)Wooden Horse (Maiden, Fat Young Man)Added appearance variations for Daruma (Maiden)Milking Machine (Maiden, Mummy, Underground Woman)Fixes & AdjustmentsFixed an issue where Small Native NPCs on the map were no longer wearing the “Triangle Hat”Fixed several visual bugsAdjusted so that training animations will now play even when a corpse is placed on the Punching BagFixed an issue where H scenes between Young Men and pregnant Female Natives were not playingAdjusted so that Androids will no longer start riotsAdjusted the “Breeding” job so that Milking Machines with full food and hydration are no longer selected as workplacesAdjusted so that the food and hydration values of NPCs placed in the Milking Machine are now displayedExternal Content UpdateAdded pregnancy support and facility compatibility for several NPCsGallows: +5 compatible NPCsGuillotine: +5 compatible NPCsHooks: +5 compatible NPCsPunching Bag: +5 compatible NPCsWooden Horse: +2 compatible NPCsMilking Machine: +2 compatible NPCsPregnancy: +3 compatible NPCs",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1828894815567183",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1825727806704926",
      "title": "update v0.5.8.2 [beta]",
      "title_en": "update v0.5.8.2 [beta]",
      "date": 1772030092,
      "date_str": "2026-02-26 06:34",
      "author": "emadeplus",
      "content": "修复安卓机器人 H 场景中脖子和头部缩放值未正确应用、阴茎颜色显示异常等问题。修复安卓机器人 A 型和 C 型发型编辑加载错误。修复巨人头部在安卓制造中脖子缩放值不正确。修复瓶子（花）效果计算错误。",
      "content_en": "Bug Fixes & AdjustmentsFixed an issue in Android H scenes where the neck and head scale values were not applied correctlyFixed an issue in Android H scenes where the penis color was not displayed correctlyFixed an issue where hairstyle edits for Android Type-A and Type-C were not loading properlyFixed incorrect neck scale values when using a Giant head in Android productionFixed an issue where the effect of the item “Bottle (Flower)” was not calculated correctly",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1825727806704926",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1825093633197919",
      "title": "update v0.5.8.1 [beta]",
      "title_en": "update v0.5.8.1 [beta]",
      "date": 1771946725,
      "date_str": "2026-02-25 07:25",
      "author": "emadeplus",
      "content": "新增高大青年和大型男孩的安卓机器人应用。修复多个视觉 Bug、安卓机器人激光发射位置偏移。调整后 NPC 在场景中被搬运和丢弃后重新加载时不会立即消失。调整安卓机器人脖子粗细和长度更自然。卡娜和露露的发型现在可应用于安卓机器人。",
      "content_en": "AdditionsAdded new Android applications for:Large Young ManLarge BoyFixes & AdjustmentsFixed several visual bugsFixed an issue where the Android’s laser firing position was misalignedAdjusted so that NPCs carried and dropped within a stage will no longer disappear immediately after reloading the stageAdjusted the Android’s neck thickness and length to appear more naturalAdjusted so that hairstyles other than the default for Kana and Lulu can now be applied to Androids",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1825093633197919",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1825093633192994",
      "title": "update v0.5.8 [beta]",
      "title_en": "update v0.5.8 [beta]",
      "date": 1771823656,
      "date_str": "2026-02-23 21:14",
      "author": "emadeplus",
      "content": "新增 H 场景：男性×原型 B 型（普通）、男性×原型 C 型（普通）、男性×安卓机器人（普通）。新增约 20 种新物品。新增大型女性原住民、大型男性原住民、胖墩的拆解选项。新增大型女性原住民、胖墩、年轻女士、女儿的安卓机器人应用。修复多个视觉和稳定性问题。",
      "content_en": "Beta Version NoticeThis version requires opting into the beta branch to play. Please note that stability is not guaranteed, and we strongly recommend using a separate save file when playing this version.New H ScenesMale × Prototype Type B (Normal)Male × Prototype Type C (Normal)Male × Android (Normal)AdditionsAdded approximately 20 new itemsAdded Dismantling options for:Large Female NativeLarge Male NativeChubby GuyAdded new Android applications for:Large Female NativeChubby GuyYoung LadyDaughterFixes & AdjustmentsFixed an issue where unnecessary .xml files inside the Visiting data folder could prevent Visiting data from loading correctlyAdjusted so that status points can be allocated in increments of 100 (Shift + Ctrl Click)Fixed several visual bugsAdjusted the display of item tooltip text(External Content)New H scene *1",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1825093633192994",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1822556746163669",
      "title": "update v0.5.7 [beta]",
      "title_en": "update v0.5.7 [beta]",
      "date": 1769249111,
      "date_str": "2026-01-25 02:05",
      "author": "emadeplus",
      "content": "热修复：修复了加载零同伴 NPC 的场景数据时导致拜访数据加载失败、拜访功能不可用的关键 Bug。",
      "content_en": "HotfixFixed a critical bug related to the Visiting feature.FixesFixed an issue where loading stage data with zero companion NPCs caused the Visiting data to fail to load properly, making the Visiting feature unusable.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1822556746163669",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1821922921818961",
      "title": "update v0.5.6 [beta]",
      "title_en": "update v0.5.6 [beta]",
      "date": 1768701769,
      "date_str": "2026-01-18 18:02",
      "author": "emadeplus",
      "content": "修复了服装装备颜色未正确应用的问题（当前设定为基础装备的颜色应用于服装）。",
      "content_en": "Bug FixFixed an issue where apparel equipment colors were not applied correctly.(Under the current specification, the base equipment’s color is applied to apparel.)",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821922921818961",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1821922921818133",
      "title": "update v0.5.5 [beta]",
      "title_en": "update v0.5.5 [beta]",
      "date": 1768662952,
      "date_str": "2026-01-18 07:15",
      "author": "emadeplus",
      "content": "新增按 Q 键召唤追随者和等待中主角的功能。修复简易房屋内有 NPC 时仍可被移动的问题。现在可以与等待中的主角在室内进行 H 场景。修复了约娜或男性克隆体残留在存档中的错误处理。",
      "content_en": "Bug FixesSeveral bug fixes have been implemented.AdditionsAdded a feature to call followers and waiting protagonists (Accessible via the Q key)Fixes & AdjustmentsFixed an issue where Simple Houses could be moved even when NPCs were insideAdjusted so that H scenes can now be performed indoors with a waiting protagonistFixed an issue where, if Yona or Male Player clones remained in save data due to an error, they are now converted into a Young Lady and a Young Man upon loadingAdded error-handling measures when loading Visiting data from the WorkshopAdjusted so that the name of the selected Visiting data is now displayed when chosenFixed an issue where the Young Lady was not targeted during raids even when equipped with a Monster-Attracting OrnamentFixed an issue where the Young Lady’s bow did not fire from the correct positionFixed an issue where H scene counts were not being recorded in Reika’s and Keigo’s event H scenesData Fix CommandIf you have multiple Nami characters, running the following command will convert all but one Nami into “Slender Young Lady”:/fixallnami When executed with a Nami selected, the selected Nami will remain unchanged, and all other Nami will be converted into “Slender Maiden”.After executing the command, please save and reload the game to restore the friend list correctly.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821922921818133",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1821288646585430",
      "title": "update v0.5.4 [beta]",
      "title_en": "update v0.5.4 [beta]",
      "date": 1768213898,
      "date_str": "2026-01-13 02:31",
      "author": "emadeplus",
      "content": "热修复：修复树精女王治疗技能无法治疗友方、流浪原住民为父亲时成年儿子模型生成错误、奈米事件未完成时关闭 H 场景锁定导致 H 场景异常、年轻女士近战搜索范围不正确等问题。",
      "content_en": "HotfixSeveral critical bugs have been prioritized and fixed.Fixes & AdjustmentsFixed an issue where allies were not healed by the Ent Queen’s healing skillFixed an issue where, when a wandering Native was the father, the grown-up son’s model was not generated correctlyFixed an issue where, before completing Nami’s event, inviting Nami for an H scene while “Sex Scene Lock” was turned off could cause the H scene to malfunctionFixed an issue where the Young Lady’s melee attack search range was not setFixed several visual bugsAdjusted so that Takumi’s son now grows into a “Chubby guy”About Data FixesIf you already have multiple Takumi characters, running the following command will change all Takumi characters except the selected one into “Chubby guy”:/fixalltakumi When executed with a Takumi selected, the selected Takumi will remain unchanged, and all other Takumi will be converted into “Chubby guy”.After running the command, please save and reload the game to restore the friend list correctly.Having multiple Takumi characters is not a critical issue, but converting them into “Chubby guy” allows actions such as carrying to function properly.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821288646585430",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1821288646582907",
      "title": "update v0.5.3 [beta]",
      "title_en": "update v0.5.3 [beta]",
      "date": 1768057117,
      "date_str": "2026-01-11 06:58",
      "author": "emadeplus",
      "content": "热修复：修复约娜×男性（传教士体位）H 场景中部分后发动画不正确、怀孕女性原住民（孕肚尚未可见时）H 动画错误使用普通动画。所有角色现在可以携带避孕药。修复约娜加载存档后怀孕状态未正确显示等问题。",
      "content_en": "HotfixA critical bug has been fixed.Fixes & AdjustmentsFixed an issue in Yona × Male (Missionary) H scenes where some back hair parts were not animated correctlyFixed an issue where H animations for pregnant Female Natives (before the belly becomes visible) were incorrectly using normal H animationsAdjusted so that all characters can now carry contraceptivesFixed an issue where Yona’s pregnancy state was not visually reflected after loading a saveAdjusted so that the protagonist’s maturity value (the number shown in parentheses after the name) is now saved correctlyFixed several visual bugsAdjusted so that some NPCs can now use the rejuvenation potionFixed an issue where attempting to restrain Shino during an event could cause progression to become stuckAdjusted so that Yona now wears clothing on the Workshop creation screen",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821288646582907",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1821288646582323",
      "title": "update v0.5.2 [beta]",
      "title_en": "update v0.5.2 [beta]",
      "date": 1768020079,
      "date_str": "2026-01-10 20:41",
      "author": "emadeplus",
      "content": "修复约娜×男性（传教士体位）H 场景后发动画不正确、老年女性原住民 H 场景不显示胸部、约娜×男性事件中非控制角色有时不出现、少女所生 NPC 类型未正确设置、少女无法放置在架子和椅子上、语音音量等问题。",
      "content_en": "Bug Fixes & AdjustmentsFixed an issue in Yona × Male (Missionary) H scenes where some back hair parts were not animated correctlyFixed an issue where the chest was no longer displayed during Elder Native Woman H scenesFixed an issue in Yona × Male events where non-controlled characters could sometimes fail to appearFixed an issue where NPCs born from the Maiden did not have their type properly setFixed an issue where the Maiden could not be placed on racks or chairsFixed an issue where voice audio was not played correctly when using the Flesh ToiletAdjusted Workshop stage upload thumbnails so that the title and language text are now displayed",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821288646582323",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1821288646581081",
      "title": "update v0.5.1 [beta]",
      "title_en": "update v0.5.1 [beta]",
      "date": 1767969148,
      "date_str": "2026-01-10 06:32",
      "author": "emadeplus",
      "content": "热修复：修复安装正确 DLC 版本后标题画面仍出现 DLC 更新按钮、部分故事文本换行显示不正确、拆除老年男性原住民头部时游戏软锁定、主角之间好感度现在也会受情感影响。",
      "content_en": "HotfixWe have fixed a critical bug.Fixes & AdjustmentsFixed an issue where the DLC update button could appear on the title screen even when the correct DLC version was installedFixed an issue where line breaks in some story text were not displayed correctlyFixed a bug where the game could soft-lock when dismantling the Elder Native Man’s headAdjusted so that affinity now increases/decreases from emotions between protagonists as well",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821288646581081",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1821288646580317",
      "title": "update v0.5 [beta]",
      "title_en": "update v0.5 [beta]",
      "date": 1767947429,
      "date_str": "2026-01-10 00:30",
      "author": "emadeplus",
      "content": "重大更新！新增约娜×男性（普通）×3 的 H 场景。新增约娜怀孕与分娩系统、拜访数据的创意工坊上传功能、约娜×男性事件。拆解支持年轻女士。达摩支持年轻女士。年轻女士可与拓海、原住民、大型原住民等多种 NPC 进行 H。新增 30+ 新物品、4 个新 NPC（含女儿 NPC）。扩建和新增多个区域。大量修复与调整。",
      "content_en": "Beta Version NoticeThis version requires opting into the beta branch to play. Please note that stability is not guaranteed, and we strongly recommend using a separate save file when playing this version.New H ScenesYona × Man (Normal) × 3New FeaturesPregnancy and childbirth system for YonaWorkshop upload feature for Visiting dataYona × Man eventsDismantling (Young Lady)Daruma (Young Lady)Enabled the Young Lady to have sex with several NPCs (Takumi, Native, Large Native, Small Native, Young Man, Elder Native, Large Young Man) Note: Young Lady graphics are not yet implemented in some scenes.Enabled Yona × Takumi (Normal H)Fixes & AdjustmentsFixed an issue where Small Native legs could no longer be dismantledAdjusted Boss Native × Yona H scene so that Kana is no longer shown after being rescuedFixed unstable behavior when sounds were played repeatedlyAdjusted so that tokens cannot be brought along when visitingFixed an issue where the protagonist’s dialogue editing could not be accessed from StatusAdjusted so that reopening Dialogue Edit restores the previously selected tabDisplay Pregnancy Progress Rate in the Status details panelFixed an issue where the appearance of the Elder Native Woman was not loaded correctly in the Body RackFixed an issue where Takumi’s Aphrodisiac Bag was not being properly detectedRaid ModeFixed an issue where NPCs set to Survivor type would stand back up after a certain time even after dying(External Content)New 2 NPCsFemale Native NPCs can now equip several bowsDismantling (2 NPCs)Daruma (2 NPCs)",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1821288646580317",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1815580768280873",
      "title": "update v0.4.5.6 [beta]",
      "title_en": "update v0.4.5.6 [beta]",
      "date": 1762485002,
      "date_str": "2025-11-07 19:10",
      "author": "emadeplus",
      "content": "修复了加载存档后追随者在玩家附近位置不正确的关键 Bug。",
      "content_en": "We have fixed a critical bug.FixesFixed an issue where followers were not positioned correctly near the player after loading a saved game.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1815580768280873",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1815580768263368",
      "title": "update v0.4.5.5 [beta]",
      "title_en": "update v0.4.5.5 [beta]",
      "date": 1762439791,
      "date_str": "2025-11-07 06:36",
      "author": "emadeplus",
      "content": "修复了诅咒之手和死神之镰等技能导致的接触伤害命中检测未正确处理的关键 Bug。",
      "content_en": "We have fixed a critical bug.FixesFixed an issue where contact damage hit detection caused by skills such as Cursed Hand and Reaper’s Scythe was not processed correctly.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1815580768263368",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1815580768260014",
      "title": "update v0.4.5.4 [beta]",
      "title_en": "update v0.4.5.4 [beta]",
      "date": 1762431578,
      "date_str": "2025-11-07 04:19",
      "author": "emadeplus",
      "content": "新增掠夺者皮革套装。修正多处本地化文本。修复接触伤害（诅咒罐子、混沌藤蔓）误伤漫游 NPC、小动物放入背包存档时参数重置、约娜服装数据加载异常。调整玲香 H 场景使丝带装备正确显示。",
      "content_en": "We have fixed several critical bugs.AdditionsOutfit: Raider’s Leather OutfitFixes & AdjustmentsCorrected several localization textsFixed an issue where contact damage (e.g., Cursed Jar, Chaos Vines) could damage wandering NPCsFixed a bug where saving with a small animal NPC in the player’s backpack could reset the animal’s parametersFixed an issue in the Apparel feature where Yona’s apparel data might fail to load correctlyAdjusted Reika’s H scene so that Reika’s ribbon equipment is now properly applied",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1815580768260014",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1815034432955954",
      "title": "update v0.4.5.3 [beta]",
      "title_en": "update v0.4.5.3 [beta]",
      "date": 1762053592,
      "date_str": "2025-11-02 19:19",
      "author": "emadeplus",
      "content": "修复对话编辑功能中各选项描述未显示、自定义对话 NPC 的 NPC 菜单新增对话编辑按钮。原住民姐姐眼中高光未显示。混沌戒指新增 F 攻击。玩具锤新增特殊效果。突袭模式下幸存者类型 NPC 不会变为敌对。大量修复与调整。",
      "content_en": "Fixes & AdjustmentsGeneralFixed an issue where descriptions for each option in the Dialogue Editing feature were not displayedAdjusted so that NPCs with custom dialogue now show a “Dialogue Edit” button in the NPC menuFixed an issue where the highlight in the eyes of the Elder Sister Native was not displayedAdded an F attack to the Chaos RingAdded a special effect to the Toy HammerRaid ModeAdjusted so that NPCs set to “Survivor type” will not become hostile and will instead use visiting dialogue linesAdjusted so that Yona can now be interacted with (R key) when downed in Raid ModeAdjusted so that companions brought along can now follow and carry othersWorkshopAdjusted so that uploaded background items will now have their tag fixed to “decoration” only",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1815034432955954",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1814309641529562",
      "title": "update v0.4.5.2 [beta]",
      "title_en": "update v0.4.5.2 [beta]",
      "date": 1761460570,
      "date_str": "2025-10-26 22:36",
      "author": "emadeplus",
      "content": "修复拆除卡娜头部时游戏卡死的关键 Bug。修复白虎兜帽和白虎耳缺失材料数量设置。修复高大青年舞蹈动画视觉 Bug。卡娜和露露的胸部部件现在可应用于安卓机器人。露露的尸体可以搬运。修复木乃伊拆除头部按钮不显示。",
      "content_en": "We fixed a critical bug.Fixes & AdjustmentsFixed a bug where the game could freeze when dismantling Kana’s headFixed missing material quantity settings for White Tiger Hood and White Tiger EarsFixed a visual bug related to the large young man’s dance animationAdjusted so that Kana’s and Lulu’s chest parts can now be applied to androidsMade Lulu’s corpse carryableFixed an issue where the “Dismantle Head” button for Mummy was not displayed",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1814309641529562",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1814309641515512",
      "title": "update v0.4.5.1 [beta]",
      "title_en": "update v0.4.5.1 [beta]",
      "date": 1761422009,
      "date_str": "2025-10-26 11:53",
      "author": "emadeplus",
      "content": "修复卡娜事件不消耗衣物、从第二次对话到复活露露再返回卡娜时事件不触发（可通过存档再加载解决）、卡娜加入时临时生成的部落首领未正确删除、卡娜凳子未被设为椅子类型物体等问题。",
      "content_en": "We fixed a critical bug.Fixes & AdjustmentsFixed a bug where Kana’s event did not consume clothing as intendedFixed an issue where Kana’s event would not trigger if the player went from the second conversation with Kana to reviving Lulu and returning to Kana without loading once (this can be resolved by saving and loading)Fixed an issue where a temporarily generated Tribal Boss was not deleted properly when Kana joined the partyFixed an issue where “Kana’s Stool” was not set as a chair-type objectFixed incorrect material requirements for “White Tiger Hood” and “White Tiger Ears”Fixed a bug where losing the battle after using “Scream” in Kana’s event caused incorrect behaviorFixed several text errors in event dialogueFixed a bug where the H scene with restrained Sally could not be triggeredFixed an issue where conversations about liked/disliked people with NPCs could cause a soft lock",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1814309641515512",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1814309641501964",
      "title": "update v0.4.5 [beta]",
      "title_en": "update v0.4.5 [beta]",
      "date": 1761385848,
      "date_str": "2025-10-26 01:50",
      "author": "emadeplus",
      "content": "新增 H 场景：男性×被吊起的蓝发女孩（普通+强制）、男性×被吊起的粉发女孩（普通×2）、约娜×高大青年（普通）。新增对话编辑功能。新增被部落首领捕获的女孩事件。新增 2 个新 NPC 和多种新物品。新增拜访功能原型版（纯本地系统，无需联网）。修复多个视觉 Bug。调整 NPC 行为使攻击动画即使目标丢失也会播放完成。修复首领战结果处理异常。根据主角等级对袭击者数量设置上限。修复制造安卓机器人时使用已驯服动物导致控制问题。加载时停止渲染以减轻压力。Unity 引擎更新至安全版本。",
      "content_en": "To play this version, you need to switch to the beta branch. Please note that this version may be unstable, so we recommend using a separate save file when playing. New H ScenesMale × Hanged Blue-Haired Girl (Normal)Male × Hanged Blue-Haired Girl (Forced)Male × Hanged Pink-Haired Girl (Normal ×2)Yona × Large Young Man (Normal)New FeaturesAdded Dialogue Editing functionAdded Event for the girl captured by the Tribal BossAdded 2 new NPCsAdded several new itemsAdded a prototype version of the Visiting feature.(This is a local system and does not use online connectivity.)Fixes & AdjustmentsFixed several visual bugsAdjusted NPC behavior so that attack animations now play to completion even if the target is lost mid-actionFixed an issue where boss battle outcomes were sometimes not processed correctlyAdded an upper limit to the number of raiders that appear based on the protagonist’s levelFixed a bug where using a tamed animal in android creation could cause control issuesAdjusted the system to stop rendering the game scene during loading, reducing load-time stressUpdated the Unity engine to a secure version (vulnerability fix)",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1814309641501964",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1808601382442963",
      "title": "update v0.4.4.8 [beta]",
      "title_en": "update v0.4.4.8 [beta]",
      "date": 1755777449,
      "date_str": "2025-08-22 03:57",
      "author": "emadeplus",
      "content": "紧急更新：新增创意工坊 NPC 加载失败的故障保护错误处理（此问题可能导致创意工坊 NPC 无法加载，甚至存档数据加载失败）。",
      "content_en": "We’ve released an emergency update to address a critical bug.■ FixesAdded fail-safe error handling for cases where loading Workshop NPCs fails. (This issue could prevent Workshop NPCs from loading and, in some cases, cause save data to fail to load.)",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1808601382442963",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1808061939470123",
      "title": "update v0.4.4.7 [beta]",
      "title_en": "update v0.4.4.7 [beta]",
      "date": 1755524441,
      "date_str": "2025-08-19 05:40",
      "author": "emadeplus",
      "content": "紧急热修复：修复多个视觉 Bug。修复创意工坊 NPC 创建模式中无法加载 NPC 的问题。",
      "content_en": "We identified a critical bug and have released an urgent hotfix.■ Fixes & AdjustmentsFixed several visual bugs.Fixed a bug where NPCs could not be loaded in the Workshop NPC creation mode.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1808061939470123",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1808061939430471",
      "title": "update v0.4.4.6 [beta]",
      "title_en": "update v0.4.4.6 [beta]",
      "date": 1755416923,
      "date_str": "2025-08-17 23:48",
      "author": "emadeplus",
      "content": "修复多个阻碍游戏进程的 Bug：修正多处本地化文本。未安装 DLC 进入游戏时显示角色删除日志。修复背包吸尘器可能覆盖玩家或箱子槽位内容。新增击晕动物无法正确收集的错误处理。新增 Boss 战中友军伤害的错误处理。修复切换地图时音效停止等问题。",
      "content_en": "Several gameplay-blocking bugs have been fixed.■ Fixes & AdjustmentsCorrected several localization texts.Adjusted so that if DLC is not applied when entering the game, a character deletion log will now be displayed.Fixed a bug where using the backpack vacuum could sometimes overwrite the contents of player or chest slots.Added error handling for cases where knocked-out animals could not be properly collected.Added error handling for friendly fire during boss battles.Fixed an issue where switching to the protagonist with arrows stuck in them would cause additional damage equal to the number of arrows.Fixed a bug where NPC workshop textures would not load correctly when Quality was set to Middle or lower.Fixed an issue where Reika and Mary could no longer equip glasses.Improved loading so that workshop NPC textures appear cleaner.Adjusted Build Manager so platforms and cooking can be loaded separately.Moved the maid outfit from the “Halloween Workbench” to the “Cute Workbench.”Adjusted so that only NPCs currently existing as allies are displayed in the equipable NPC list.Adjusted damage calculation method for allied Reapers.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1808061939430471",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1807332909700610",
      "title": "update v0.4.4.5 [beta]",
      "title_en": "update v0.4.4.5 [beta]",
      "date": 1754920295,
      "date_str": "2025-08-12 05:51",
      "author": "emadeplus",
      "content": "修复血肉收集器物品数量设置错误。修复根据操作系统语言设置可能导致外部数据无法加载的问题。",
      "content_en": "Fixed incorrect item quantity settings for the Flesh Collector.Fixed an issue where external data might not load depending on the OS language settings.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909700610",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1807332909694949",
      "title": "update v0.4.4.4 [beta]",
      "title_en": "update v0.4.4.4 [beta]",
      "date": 1754904808,
      "date_str": "2025-08-12 01:33",
      "author": "emadeplus",
      "content": "修复装备精灵会意外应用避孕效果的问题。布料存储现在可以用口袋扩展。修复语言非日语时创意工坊物品提示不显示。修复袭击中生成的 NPC 数据错误。修复女性原住民女孩无法装备眼镜物品。修复手动关闭背包时界面残留等问题。",
      "content_en": "Several bug fixes have been implemented.■ Fixes & AdjustmentsFixed a bug where equipping “Wisp” would unintentionally apply the contraceptive effect.Adjusted so that cloth storage can now be expanded with a Pocket.Fixed an issue where workshop item tooltips would not display when the language was set to anything other than Japanese.Fixed incorrect data for NPCs spawned during raids.Fixed an issue where female native girls could no longer equip glasses items.Fixed a bug where manually closing the map during fast travel would cause the map to remain open after fast travel.Fixed a bug where male natives’ throwing attacks had no hit detection.Added throwing and bow attack animations for young men.Fixed several visual bugs.Adjusted so that Wisp becomes hidden when carrying an NPC equipped with one.Adjusted so that young men can now perform normal H scenes with other NPCs.■ External Data Updatev1.01",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909694949",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1807332909643483",
      "title": "update v0.4.4.3 [beta]",
      "title_en": "update v0.4.4.3 [beta]",
      "date": 1754763950,
      "date_str": "2025-08-10 10:25",
      "author": "emadeplus",
      "content": "紧急热修复：修复无装备 NPC 加载时服装外观未应用、服装系统切换装备保存数据错误、友方 NPC 敌人检测被死神灵气效果阻挡。调整精灵装备浮动位置。修复友方 NPC 动画速度在战斗后偶发不恢复等问题。",
      "content_en": "We identified a critical bug and have released an urgent hotfix.■ Fixes & AdjustmentsFixed an issue where apparel visuals were not applied on load for NPCs with no equipment.Fixed a bug where swapping gear in the Apparel system could fail to save data correctly.Fixed an issue where allied NPCs’ enemy detection was being blocked by the Reaper’s aura effect.Adjusted the floating position when equipping “Wisp.”Fixed an issue where allied NPCs’ animation speed sometimes didn’t return to normal after a raid.Fixed a bug where playtime in save data would stop counting beyond a certain duration.Adjusted so the Ent Queen can equip items that are available to all characters.Fixed a bug where NPC stats calculated from the map level were not computed correctly at spawn.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909643483",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1807332909610077",
      "title": "update v0.4.4.2 [beta]",
      "title_en": "update v0.4.4.2 [beta]",
      "date": 1754673279,
      "date_str": "2025-08-09 09:14",
      "author": "emadeplus",
      "content": "紧急热修复：修复使用突袭号角不触发袭击、黑色幕帘拱门无法正确放置、对友方大型女性原住民按 R 键导致游戏卡死。修复多个视觉 Bug。",
      "content_en": "We identified a critical bug and have released an urgent hotfix.■ FixesFixed a bug where raids would not occur when using the \"Raid Horn.\"Fixed a bug where the \"Black Curtain Arch\" could not be placed correctly.Fixed an issue where using R on an allied large native woman would cause the game to get stuck.Fixed several visual bugs.To play this version, you need to switch to the beta branch. Please note that this version may be unstable, so we recommend using a separate save file when playing. ",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909610077",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1807332909601686",
      "title": "update v 0.4.4.1 [beta]",
      "title_en": "update v 0.4.4.1 [beta]",
      "date": 1754652968,
      "date_str": "2025-08-09 03:36",
      "author": "emadeplus",
      "content": "紧急热修复：修复楼梯和灯光参数加载不正确、口袋物品无法用于箱子等存储容器的问题。",
      "content_en": "We identified a critical bug and have released an urgent hotfix.FixesFixed an issue where parameters for stairs and lights were not loading correctly.Fixed a bug that prevented Pocket items from being used on chests and similar storage.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909601686",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1807332909599651",
      "title": "update v0.4.4 [beta]",
      "title_en": "update v0.4.4 [beta]",
      "date": 1754646783,
      "date_str": "2025-08-09 01:53",
      "author": "emadeplus",
      "content": "新增 H 场景：男性×死神（普通）。新增服装搭配功能、原创 NPC 加载功能、原创 NPC 的创意工坊上传与订阅功能。新增死神突袭事件和多种新物品。新增死神事件。修复多个视觉 Bug。怀孕期间若没有可见孕肚仍然可以进行 H。调整多个系统细节。",
      "content_en": "To play this version, you need to switch to the beta branch. Please note that this version may be unstable, so we recommend using a separate save file when playing. ■ Added H ScenesMan × Reaper (Normal)■ AdditionsOutfit Coordination featureOriginal NPC loading featureWorkshop upload and subscription feature for Original NPCsReaper RaidSeveral new itemsReaper Event■ Fixes & AdjustmentsFixed several visual bugsAdjusted so that characters can still have sex during pregnancy if they don’t have a visible pregnant bellyAdjusted so that young men can perform forced H on large native womenAdjusted so that “Pocket” items can be used in chest and storage slotsFixed an issue where shurikens thrown by npcs would not hit enemiesFixed a bug where Sally’s throw attack would affect alliesAdjusted so that the HP display of NPCs being attacked by the player is always updatedFixed warning text from blocking clicksFixed an issue where using food items on a food storage box could exceed its maximum capacityFixed an issue where emotions would still affect NPCs who had been banished and become inactiveFixed a bug where the numeric input fields for colors in character edit could be hidden behind in-game objects■ External Content UpdateAdded 4 new H scenesFor more details, please check the official Discord or other channels.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909599651",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1807332909591954",
      "title": "update v0.4.3.2",
      "title_en": "update v0.4.3.2",
      "date": 1754626558,
      "date_str": "2025-08-08 20:15",
      "author": "emadeplus",
      "content": "游戏默认版本已更新至 v0.4.3.2。",
      "content_en": "The default build of the game has been updated to version v0.4.3.2. For detailed update information, please refer to our previous posts.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1807332909591954",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1801617199476210",
      "title": "update v0.4.3.2[beta]",
      "title_en": "update v0.4.3.2[beta]",
      "date": 1749349315,
      "date_str": "2025-06-08 18:21",
      "author": "emadeplus",
      "content": "紧急修复：修复画质设为中等或以下时创意工坊物品纹理无法渲染的关键 Bug。",
      "content_en": "We’ve urgently fixed a critical bug:■ FixesFixed a bug where Workshop item textures would fail to render when the Quality setting was set to Middle or below.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1801617199476210",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1801617199473988",
      "title": "update v0.4.3.1[beta]",
      "title_en": "update v0.4.3.1[beta]",
      "date": 1749343452,
      "date_str": "2025-06-08 16:44",
      "author": "emadeplus",
      "content": "紧急修复：修正了与倒地 NPC 交互时界面位置显示不正确的问题。",
      "content_en": "We’ve urgently fixed a critical bug:■ FixesCorrected an issue where the UI’s position would not display properly when interacting with a downed NPC.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1801617199473988",
      "type": "🔴 热修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1801617199445166",
      "title": "update v0.4.3[beta]",
      "title_en": "update v0.4.3[beta]",
      "date": 1749266246,
      "date_str": "2025-06-07 19:17",
      "author": "emadeplus",
      "content": "修复对跟随中的 NPC 使用成长药水变形处理不生效、标题画面编辑模式中更改皮肤颜色同时改变了乳头颜色。调整 H 场景（青年男性×地下女性、青年男性×大体型女性）正确包含怀孕几率。修复建筑移动和拆除按钮等界面元素位置不正确。",
      "content_en": "Several critical bugs have been fixed.■ Fixes & AdjustmentsFixed a bug where using a growth potion on an NPC while they were being followed would prevent the transformation from processing correctly.Fixed an issue where changing skin color in the title screen edit mode also changed the nipple color to match the skinAdjusted H-scenes (Young Man x Underground Woman, Young Man x Large-Built Woman) to properly include pregnancy chanceFixed incorrect positioning of UI elements such as building move and dismantle buttonsFixed a bug where workshop item images were not displayed correctly when the quality setting was set to “Middle” or lowerFixed a bug where the durability of the weapon \"Shuriken\" was not displayedTo play this version, you need to switch to the beta branch. Please note that this version may be unstable, so we recommend using a separate save file when playing.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1801617199445166",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1801617199425917",
      "title": "update v0.4.2[beta]",
      "title_en": "update v0.4.2[beta]",
      "date": 1749216422,
      "date_str": "2025-06-07 05:27",
      "author": "emadeplus",
      "content": "新增大型女性原住民怀孕、地下女性怀孕。新增 NPC：大型青年男性、动物×1、地下青年男性。新增小太刀重攻击。装备手里剑的 NPC 现在可以投掷。部分 NPC 可改变身体颜色。修复叠加食物物品被不同食物使用、监狱 NPC 跟随切换地图时有时消失、喂食器中牛奶被消耗完后空桶残留在容器中等问题。",
      "content_en": "To play this version, you must switch the game to the beta branch. Due to many changes that may affect game data, please make sure to use a separate save file.■ AdditionsPregnancy for the large female nativePregnancy for the underground womanNew NPC: Large young manNew NPC: Animal (x1)New NPC: Underground young manAdded heavy attack for KodachiNPCs equipped with shuriken can now throw themSome NPCs can now have their body color changed■ Fixes & AdjustmentsFixed a bug where food items stacked by the Meal Distributor could not exceed 1000Reduced memory usage of workshop items (texture compression)Improved NPC movement behavior to reduce sliding when idle on sloped terrainAdjusted rendering order so that the position of NPCs and the horse device displays more accuratelyFixed a bug where human body parts stored in the player's bag wouldn't save properlyDisabled the birth button during paused stateFixed an issue where pause overlay text could not be hidden during eventsFixed a bug where placed items would become invisible when moved too far from the playerMade Little & Nikki’s outfits equippable. (If they have already joined your party, they may appear naked. Little’s outfit can be crafted from the native elder woman.)■ External Content Update3 new H-scenes added4 new NPCs added For more details, please check the official Discord or other announcements.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1801617199425917",
      "type": "🔵 小更新",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1797185861720254",
      "title": "update v0.4.1[beta]",
      "title_en": "update v0.4.1[beta]",
      "date": 1745112427,
      "date_str": "2025-04-20 17:27",
      "author": "emadeplus",
      "content": "修复餐食分配器食物堆叠上限 1000、多处本地化错误、多个视觉 Bug、无法访问枯树物品栏、男主角×奈米 H 动画中部分音效缺失等问题。",
      "content_en": "■ Fixes & Adjustments -Fixed a bug where the food stack of the Meal Distributor was capped at 1000 -Fixed several localization errors -Fixed several visual bugs -Fixed a bug where it was impossible to access the inventory of “Withered Tree” -Fixed an issue where some sound effects were missing in the H-animation of Male Protagonist x Nami",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1797185861720254",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1797185861702008",
      "title": "update v0.4 [beta]",
      "title_en": "update v0.4 [beta]",
      "date": 1745062466,
      "date_str": "2025-04-20 03:34",
      "author": "emadeplus",
      "content": "v0.3.4 已设为默认版本。新增奈米与男主角支线剧情、奈米与约娜支线剧情。新增可骑乘马匹（女性原住民、地下女性、原住民女首领）。约 20 种新道具。新增 H 场景：约娜×奈米（普通）、男主角×奈米（普通+强制），完成新增剧情后解锁。",
      "content_en": "v0.3.4 has been set as the default version. To play this version, you need to switch to the beta branch. Please note that this version may be unstable, so we recommend using a separate save file when playing. ■ Additions -Substory between Nami and the male protagonist -Substory between Nami and Yona -Usable horse (female natives, underground women, and native boss lady) -Around 20 new items ■ New H-Scenes -Yona x Nami (normal H) -Male Protagonist x Nami (normal H) -Male Protagonist x Nami (forced H) These H-scenes become available after completing the newly added storylines. ■ Fixes & Adjustments -Fixed a bug where the UI would remain visible if an NPC woke up during a sleep rape event -Fixed an issue where downed skeletons with custom colors would partially revert to their original color -Fixed several bugs occurring during battle events with the gorilla -Reduced memory usage -Fixed several visual bugs -Corrected some localization issues -You can now trade items with the trader 10 times in a row using Shift + click",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1797185861702008",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1793384379500977",
      "title": "update v0.3.4 [beta]",
      "title_en": "update v0.3.4 [beta]",
      "date": 1741610232,
      "date_str": "2025-03-11 04:37",
      "author": "emadeplus",
      "content": "修复关键 Bug：敌人原住民茅草屋内地板纹理错误、NPC 昏迷后被擒拿不能恢复正确状态、在 v0.3 之前存档上执行树精之王任务时若不跟随巨人或爱路线可能导致事件不一致、树精之王地下战后约娜可能不可见或控制权切换到男主角等问题。",
      "content_en": "Fixed critical bugs. -Fixed a texture error on the floor inside enemy natives’ thatched houses. -Fixed an issue where NPCs did not return to the correct state after being grappled while unconscious. -Fixed a bug where performing the Ent King quest on save data from before v0.3 could cause inconsistencies in events when not following the Giant or Love route. -Fixed an issue where Yona could become invisible or control could switch to the male protagonist underground after the Ent King’s underground event.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1793384379500977",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1793384379430939",
      "title": "update v0.3.3 [beta]",
      "title_en": "update v0.3.3 [beta]",
      "date": 1741419816,
      "date_str": "2025-03-08 23:43",
      "author": "emadeplus",
      "content": "修复关键 Bug：若拓海存活但未获救则无法进入树精之王战。修复茅草屋内地板纹理错误。修复拓海不在时桥梁建设事件中止的问题。",
      "content_en": "Fixed critical bugs. ■Fixes & Adjustments -Adjusted so that if Takumi is alive but has not been rescued, the Entking battle cannot be entered. -Fixed a texture error on the floor inside the thatched house. -Fixed an issue where the bridge construction event would stop if Takumi was not present.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1793384379430939",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1793384379404676",
      "title": "update v0.3.2 [beta]",
      "title_en": "update v0.3.2 [beta]",
      "date": 1741350062,
      "date_str": "2025-03-08 04:21",
      "author": "emadeplus",
      "content": "新增奈米、玲香、志乃和大型女性原住民可应用服装和武器。新增创意工坊物品缩放功能。修复对倒地友方物品栏使用口袋会扩展受控主角背包槽位、首次与树精之王战后若通过爱路线完成巨人事件则后续树精之王事件无法推进、工坊物品筛选在分类间切换失效、睡眠侵犯事件 UI 残留、骷髅兵自定义颜色、大猩猩战斗事件异常等问题。优化内存。新增 Shift+点击与商人连续交易 10 次。",
      "content_en": "We have fixed several critical bugs. ■Additions -Applied costumes and weapons to Nami, Reika, Shino, and large-built native women. -Added a scaling function for Workshop items. ■Fixes & Adjustments -Fixed an issue where using \"Pocket\" in the inventory of a downed ally would expand the controlled protagonist's bag slots. -Fixed an issue where, after the first battle with the Entking, if the Giant's event was completed via the Love route, the subsequent events of the Entking would not progress correctly. -Fixed a bug where the Giant would remain hidden after returning from the battle until a reload. -Fixed an issue where swapping a dyed item with an undyed item at the dyeing workbench would display the previous color information on the sprite. -Fixed an issue where the circle and capacity values displayed when interacting with the food storage would sometimes not disappear. -Fixed an issue where after the first battle with the Entking, Yona's weapon remained hidden. -Fixed an issue where the quest name display was incorrect after the first battle with the Entking.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1793384379404676",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1792751526042729",
      "title": "Update v0.3.1 [beta]",
      "title_en": "Update v0.3.1 [beta]",
      "date": 1740750350,
      "date_str": "2025-03-01 05:45",
      "author": "emadeplus",
      "content": "修复战斗事件结束后非控制主角等待位置被设置在树精之王战场、从地下与树精之王战斗返回后奈米和玲香消失（存档再加载可解决）、女王事件结束后无法正常交互约娜和巨人等问题。",
      "content_en": "■Fixes & Adjustments -Fixed an issue where the non-controlled protagonist's waiting position was set to the Ent King’s battlefield after the battle event ended. -Fixed an issue where Nami and Reika would disappear after returning from the underground battle with the Ent King (can be resolved by saving & loading). -Fixed an issue where Jonah and the Giant could not be interacted with properly after the Queen event ended.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1792751526042729",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1792751526036574",
      "title": "update v0.3 [beta]",
      "title_en": "update v0.3 [beta]",
      "date": 1740735558,
      "date_str": "2025-03-01 01:39",
      "author": "emadeplus",
      "content": "新增主线故事续篇。新增拆解（青年男性）。调整雪球装饰和相框使不透明物品更清晰。修复圣诞事件文本错别字。修复圣诞事件保护驯鹿战斗中跳过功能被禁用。调整部分敌人攻击 AI。",
      "content_en": "To play this version, you need to switch to the beta version. As it may be unstable, we recommend keeping a separate save file when playing. ■ Additions - Continuation of the Main Story. - Dismantling (Young Man) ■ Fixes & Adjustments - Adjusted Snow Dome (item icon) and picture frames to display opaque items more clearly. - Fixed typos in the Santa event text. - Fixed an issue where the skip function remained disabled during the battle to protect the reindeer in the Santa event. - Adjusted enemy spawn rate during events to make them less frequent. - Fixed a bug where summoning a recovered raider NPC while the raid was still ongoing caused the raid to not end properly, leading to gameplay issues. - Fixed an issue where creating a picture frame while having the sub-inventory open displayed the icon of the first item in the sub-inventory. - Adjusted the final position of the death animation for the male protagonist and young man to be more centered on the character. - Adjusted the game so that pausing is canceled when returning to the title screen. - Fixed an issue where using the same Daruma Machine repeatedly caused the door animation position to become misaligned. - Fixed a bug where grappling an NPC during sex caused a temporary duplication of character graphics. - Fixed unnecessary scale values in the Chaos Lake and Blood Area.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1792751526036574",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1786573930683185",
      "title": "update v0.2.7",
      "title_en": "update v0.2.7",
      "date": 1734774418,
      "date_str": "2024-12-22 01:46",
      "author": "emadeplus",
      "content": "修复了卡住的 Bug，版本已更新至 v0.2.7。",
      "content_en": "The stuck bug has been fixed, and the version has been updated to v0.2.7.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1786573930683185",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1786573930682294",
      "title": "Apology for the Stuck Bug",
      "title_en": "Apology for the Stuck Bug",
      "date": 1734771127,
      "date_str": "2024-12-22 00:52",
      "author": "emadeplus",
      "content": "为 v0.2.7 更新中出现的卡顿 Bug 致歉。该问题导致玩家在砍树等操作后卡住，已临时将版本降级至 v0.2.6。正在调查问题并将尽快提供修复。",
      "content_en": "We sincerely apologize for the inconvenience caused by the stacking bug that occurred in the latest update (v0.2.7). The issue resulted in players getting stuck after actions like cutting down trees, prompting us to temporarily downgrade the version to v0.2.6. We are currently investigating the problem and will provide a fix as soon as possible. Thank you for your understanding and continued support.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1786573930682294",
      "type": "🟡 Bug修复",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1786573930679705",
      "title": "update v0.2.7",
      "title_en": "update v0.2.7",
      "date": 1734763780,
      "date_str": "2024-12-21 22:49",
      "author": "emadeplus",
      "content": "修复多个 Bug：所有 NPC（包括动物）显示详细状态页面、修复加载游戏后房屋 ID 设置不正确、NPC 交互后闪烁效果被附近 NPC 完成工作时取消、日志仅保留最多 100 条以防失控增长等。",
      "content_en": "The current build has been set as the default build. For details on the changes, please refer to previous news updates. Several bugs have been fixed. ■ Fixes and Adjustments - Adjusted to display the detailed status page for all NPCs, including animals. - Fixed a bug where house IDs were not set correctly after loading the game. - Fixed an issue where the blinking effect on an NPC after interaction would be canceled when nearby NPCs completed their works. - Adjusted logs to retain only up to 100 entries. - Added an option to toggle the display of task icons on or off. - Added an option to enable or disable the blinking effect on NPCs after interaction. - Assigned personality traits to Merry and the Reindeer, as they were previously unset. ",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1786573930679705",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1786409468866811",
      "title": "update v0.2.6 [beta]",
      "title_en": "update v0.2.6 [beta]",
      "date": 1734591017,
      "date_str": "2024-12-19 22:50",
      "author": "emadeplus",
      "content": "修复多个关键 Bug：梅莉×男性 H 场景中男性角色臀部颜色变化未正确反映、搬运进房屋的 NPC 仍保留房屋 ID、木筏无法使用、NPC 等待位置设在室外但睡在室内时存档后加载导致无法离开等问题。",
      "content_en": "Several critical bugs have been fixed. ■ Fixes and Adjustments - Fixed an issue where color changes to the male character's hips were not correctly reflected in the Merry x Male H scene. - Fixed a bug where NPCs carried inside a house retained their house ID. - Fixed an issue where rafts could not be used. - Fixed a bug where saving the game while an NPC with their waiting position set outside was sleeping inside a house caused them to remain linked to the house after loading, preventing them from using it properly. - Fixed an issue where house ID information would not update unless the status page of the status menu was open. - Adjusted so that house IDs are displayed even for thatched-roof houses.",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1786409468866811",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": false,
      "gid": "1786409468834954",
      "title": "update v0.2.5[beta]",
      "title_en": "update v0.2.5[beta]",
      "date": 1734507163,
      "date_str": "2024-12-18 23:32",
      "author": "emadeplus",
      "content": "修复多项 Bug：圣诞事件完成后礼物狩猎事件开关无法激活、从房屋物品栏召唤 NPC 时未设置召唤位置为等待位置、移除笼陷阱命中检测、更改重复任务图标颜色、NPC 装备被吸入背包时外观更新、Shift+点击商人连续交易 10 次等。",
      "content_en": "Several bug fixes have been implemented. ■ Fixes and Adjustments - Fixed a bug where the event switch for the \"Present Hunt\" could not be activated after completing the Santa Event. - Fixed an issue where summoning an NPC from the inventory inside a house did not set the summoning location as the NPC's waiting position. - Removed hit detection from cage traps. - Changed the color of repeat quest icons displayed on the map. - Adjusted so that NPC appearances update when their equipment is vacuumed using the Maid Ruck. - Adjusted so that NPCs other than raiders do not target trees. - Fixed a bug where the color of icons did not revert when moving dye workbench, picture frames, etc. - Fixed an issue where the appearance of unique NPC corpses did not load correctly. - Fixed several visual bugs. - Updated NPC status screens to display their current house ID. - Adjusted to display house IDs when interacting with your own house. - Fixed a bug where NPC colors occasionally did not revert when they were",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1786409468834954",
      "type": "🟢 主要内容",
      "manual": true
    },
    {
      "adult": true,
      "gid": "1785774543608938",
      "title": "update v0.2.4[beta]",
      "title_en": "update v0.2.4[beta]",
      "date": 1734231563,
      "date_str": "2024-12-15 18:59",
      "author": "emadeplus",
      "content": "新增 H 场景：男主角×圣诞老人（标准 H 场景）。新增圣诞老人事件、2 个新 NPC、30+ 新物品（含装饰和服饰）、相框（显示图标）。修复地图显示进行中事件图标、萨莉投掷攻击无伤害、标题画面订阅工坊列表限制 50 个等问题。新增预览模式装备预览功能。",
      "content_en": "■ Added H Content -Male Protagonist x Santa (Standard H Scene) ■ Additions -Santa Event -2 New NPCs -Over 30 New items, including new decorations and clothing items -Picture Frame (an item for displaying icons) ■ Fixes and Adjustments -Fixed a bug where event icons for ongoing events were displayed on the map. -Added damage to Sally’s throw attack. -Fixed an issue where the list of subscribed workshop items on the title screen was limited to 50 items. -Added an equipment preview function in Preview Mode. To play the beta version, you need to configure it from the properties menu. {STEAM_CLAN_IMAGE}/44906878/e362d1b886636b70ef2669ef148ed6c784246181.jpg",
      "url": "https://steamstore-a.akamaihd.net/news/externalpost/steam_community_announcements/1785774543608938",
      "type": "🟢 主要内容",
      "manual": true
    }
  ]
};
